title: InferiGang
url: https://inferi.zip
paginate: 1
baseurl: ""
permalink: pretty

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-sitemap

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

collections:
  posts:
    output: true
    permalink: /paper/:title

paginate_path: "/page/:num"

author:
  name: inferigang
  url: https://twitter.com/inferigang
  email: underworld.comp@proton.me

version: 3.0.0

nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
