url: ""
baseurl: ""
lang: en

title: InferiGang
description: The inferigang project is a group of computer science and information security enthusiasts, mainly focused on sharing information and knowledge.
languages: [en, pt]

theme_style:
    default: dark-theme

permalink: pretty

paginate: 4
paginate_path: "/blog/:num"

collections:
  posts:
    output: true
    permalink: "/post/:title"
  projects:
    output: true
  members:
    output: true

defaults:
  - scope:
      path: "_posts/"
    values:
      layout: post

  - scope:
      path: "_projects/"
    values:
      layout: project

  - scope:
      path: ""
    values:
      layout: page
      lang: en

  - scope:
      path: "pt/"
    values:
      layout: page
      lang: pt

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

